- hosts: localhost #, fedora, ubuntu
  vars:
    # Host_vars
    ansible_become_password: u
    ansible_user: "{{lookup('ansible.builtin.env', 'USER')}}"

  roles:
    - Tesseract
    - python dependencies
